CREATE SEQUENCE GESTAO.SEQ_TICKET START WITH 1 INCREMENT BY 1 MINVALUE 1;
CREATE TABLE GESTAO.TICKET
(
    ID_TICKET        NUMBER PRIMARY KEY,
    NUMERO           NUMBER         NOT NULL UNIQUE CHECK (NUMERO > 0),
    TITULO           VARCHAR2(200)  NOT NULL,
    DESCRICAO        VARCHAR2(4000) NOT NULL,
    STATUS           VARCHAR2(30)   NOT NULL CHECK (STATUS IN ('A FAZER', 'EM ANDAMENTO', 'CONCLUIDO', 'CANCELADO')),
    DATA_CRIACAO     DATE           NOT NULL,
    DATA_ATUALIZACAO DATE           NOT NULL
);

CREATE SEQUENCE GESTAO.SEQ_TAG START WITH 1 INCREMENT BY 1 MINVALUE 1;
CREATE TABLE GESTAO.TAG
(
    ID_TAG    NUMBER PRIMARY KEY,
    DESCRICAO VARCHAR2(100) NOT NULL,
    COR       VARCHAR2(10)  NOT NULL DEFAULT '#FFFFFF'
);

CREATE TABLE GESTAO.TICKET_TAG_ASSOCIATION
(
    ID_TICKET       NUMBER NOT NULL,
    ID_TAG          NUMBER NOT NULL,
    DATA_ASSOCIACAO DATE   NOT NULL DEFAULT SYSDATE,
    PRIMARY KEY (ID_TICKET, ID_TAG),
    CONSTRAINT FK_TICKET FOREIGN KEY (ID_TICKET) REFERENCES GESTAO.TICKET (ID_TICKET),
    CONSTRAINT FK_TAG FOREIGN KEY (ID_TAG) REFERENCES GESTAO.TAG (ID_TAG)
);
